---
# Test Application - Harvis v2.28.10
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harvis-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dulc3/harvis-aidev.git
    targetRevision: HEAD
    path: k8s-manifests/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-agents
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
