#!/usr/bin/env bash
# Work out FT_* settings for THIS machine and print them as an env file.
#
#   scripts/freetoken/autotune.sh                    print settings to stdout
#   scripts/freetoken/autotune.sh --write            write ~/.config/freetoken.env
#   FT_MODEL_DIR=/path/to/checkpoint autotune.sh     size the RAM check against a model
#
# Why this exists: the settings that work are a property of the box, not of FreeToken.
# The 8 GB laptop needs FT_MEMORY_RATIO=0.90 and a 2048-token prefill chunk or the
# scheduler dies on a long prompt; a 24 GB card is being wasted at those numbers. Every
# new node was otherwise going to inherit the laptop's numbers from a hardcoded script.
#
# These are starting points calibrated on the 8 GB laptop, not laws. After installing,
# run scripts/freetoken/limits.sh on the new box and put the real ceiling in the docs.
set -uo pipefail

die() { echo "autotune: $*" >&2; exit 1; }
command -v nvidia-smi >/dev/null 2>&1 || die "nvidia-smi not found — need an NVIDIA GPU and driver"

read -r VRAM_TOTAL VRAM_USED <<<"$(nvidia-smi --query-gpu=memory.total,memory.used --format=csv,noheader,nounits | head -1 | tr -d ',')"
GPU_NAME="$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)"
# VRAM held by anything that is not FreeToken. On a desktop machine this is the
# compositor and the browsers; on a headless server it is usually zero.
FT_VRAM="$(nvidia-smi --query-compute-apps=pid,used_memory --format=csv,noheader,nounits 2>/dev/null \
  | while IFS=, read -r pid mem; do
      pid="$(echo "$pid" | tr -d ' ')"; mem="$(echo "$mem" | tr -d ' ')"
      if tr '\0' ' ' < "/proc/$pid/cmdline" 2>/dev/null | grep -q 'ft serve\|freetoken'; then echo "$mem"; fi
    done | awk '{s+=$1} END{print s+0}')"
OTHER_VRAM=$(( VRAM_USED - FT_VRAM )); [ "$OTHER_VRAM" -lt 0 ] && OTHER_VRAM=0

RAM_TOTAL_MB="$(awk '/MemTotal/{printf "%d", $2/1024}' /proc/meminfo)"
CORES="$(lscpu 2>/dev/null | awk -F: '/^Core\(s\) per socket/{c=$2} /^Socket\(s\)/{s=$2} END{print (c*s)+0}')"
[ "${CORES:-0}" -lt 1 ] && CORES="$(nproc)"

MODEL_DIR="${FT_MODEL_DIR:-${FT_HOME:-}/${FT_MODEL:-}}"
MODEL_MB=0
if [ -d "$MODEL_DIR" ]; then MODEL_MB="$(du -sm "$MODEL_DIR" 2>/dev/null | awk '{print $1}')"; fi

eval "$(python3 - "$VRAM_TOTAL" "$OTHER_VRAM" "$RAM_TOTAL_MB" "$CORES" "$MODEL_MB" <<'PY'
import sys
vram, other, ram, cores, model = (int(float(x)) for x in sys.argv[1:6])

# Prefill scratch is the memory the attention kernels need for ONE chunk, on top of
# the ratio budget. It is what killed the 8 GB laptop at chunk 8192, so the chunk
# scales with the card rather than staying at FreeToken's default.
prefill = 2048 if vram <= 10240 else (4096 if vram <= 17408 else 8192)
scratch = int(450 * prefill / 2048)

# --memory-ratio caps FreeToken's budget as a fraction of TOTAL VRAM. It does NOT
# need to account for what the desktop already holds: --moe-cache-auto sizes itself
# from *free* VRAM, so another process's memory is already subtracted for it. What
# the ratio does have to leave behind is the prefill scratch (allocated outside the
# budget) plus a margin for CUDA graphs and fragmentation.
# Calibrated so the 8 GB laptop lands on 0.90, the value measured to survive a
# grounded prompt where 0.95 OOM-killed the scheduler.
safety = int(vram * 0.05)
ratio = (vram - scratch - safety) / vram
ratio = max(0.75, min(0.93, round(ratio, 2)))

# KV cache. ~20 KB/token on a GDN-hybrid model, so 16384 tokens is ~0.31 GB. Aim at
# roughly 4% of the card, clamped to sane powers of two: enough for a grounded chat
# with sources, never so much that it starves the expert cache.
target_mb = vram * 0.04
kv = 8192
for cand in (8192, 16384, 32768, 65536, 131072):
    if cand * 20 / 1024 <= target_mb:
        kv = cand
kv = max(16384, kv) if vram > 6144 else 8192

running = 2 if vram <= 12288 else (4 if vram <= 25600 else 8)
threads = max(4, min(12, cores - 2))

# The constraint people miss: expert weights live in HOST RAM, not on the card. The
# box needs the whole checkpoint resident plus room for everything else, or it swaps.
warn = ""
if model:
    need = model + 4096
    if ram < need:
        warn = ("RAM is tight: the checkpoint is %d GB and this box has %d GB. "
                "FreeToken keeps the expert weights in system RAM, so expect swapping. "
                "Want about %d GB." % (model // 1024, ram // 1024, need // 1024))
    elif ram < need + 8192:
        warn = ("RAM is workable but not roomy: %d GB checkpoint on %d GB. Leave the "
                "idle timer on so the RAM comes back between chats." % (model // 1024, ram // 1024))

print("A_PREFILL=%d" % prefill)
print("A_RATIO=%.2f" % ratio)
print("A_KV=%d" % kv)
print("A_RUNNING=%d" % running)
print("A_THREADS=%d" % threads)
print("A_SCRATCH=%d" % scratch)
print("A_WARN=%s" % repr(warn))
PY
)"

{
  echo "# Generated by scripts/freetoken/autotune.sh on $(date -Iseconds)"
  echo "# Box: $GPU_NAME, ${VRAM_TOTAL} MiB VRAM (${OTHER_VRAM} MiB held by other processes),"
  echo "#      $(( RAM_TOTAL_MB / 1024 )) GB RAM, $CORES physical cores."
  [ "$MODEL_MB" -gt 0 ] && echo "#      Checkpoint $(( MODEL_MB / 1024 )) GB at $MODEL_DIR"
  echo "#"
  echo "# Re-run scripts/freetoken/limits.sh after starting the service: these are"
  echo "# calibrated starting points, the measured ceiling is the number that counts."
  echo
  echo "FT_HOME=${FT_HOME:-\$HOME/freetoken}"
  echo "FT_MODEL=${FT_MODEL:-models/Qwen3.6-35B-A3B-NVFP4}"
  echo "# 172.17.0.1 = Docker bridge only. FreeToken has no auth: use 0.0.0.0 only"
  echo "# behind a token proxy, never on a shared or campus network."
  echo "FT_HOST=${FT_HOST:-172.17.0.1}"
  echo "FT_PORT=${FT_PORT:-1919}"
  echo "FT_MAX_RUNNING=$A_RUNNING"
  echo "FT_KV_RESERVE=$A_KV"
  echo "# One prefill chunk needs ~${A_SCRATCH} MiB outside this budget, plus a margin for"
  echo "# CUDA graphs. The ${OTHER_VRAM} MiB other processes hold is handled automatically"
  echo "# by --moe-cache-auto, which sizes itself from free VRAM."
  echo "FT_MEMORY_RATIO=$A_RATIO"
  echo "FT_MOE_THREADS=$A_THREADS"
  echo "FT_MAX_PREFILL=$A_PREFILL"
  echo "FT_IDLE_MIN=30"
  echo "FT_WATCHDOG_PROBE_MIN=10"
  echo "FT_WATCHDOG_MAX_RESTARTS=3"
  echo "FT_WATCHDOG_PROBE_TIMEOUT=45"
} > "${TMPDIR:-/tmp}/freetoken.env.autotune"

if [ "${1:-}" = "--write" ]; then
  target="$HOME/.config/freetoken.env"
  [ -f "$target" ] && cp "$target" "$target.bak.$(date +%s)" && echo "autotune: kept a backup at $target.bak.*"
  mkdir -p "$HOME/.config"
  cp "${TMPDIR:-/tmp}/freetoken.env.autotune" "$target"
  echo "autotune: wrote $target"
else
  cat "${TMPDIR:-/tmp}/freetoken.env.autotune"
fi

[ -n "$A_WARN" ] && { echo; echo "autotune: WARNING — $A_WARN" >&2; }
exit 0
