"""Render the bootstrap script that turns a fresh Linux box into a FreeToken node.

Served by ``GET /api/inference-nodes/provision-script`` so an operator can pipe it
over an existing SSH host (``remote/ssh_manager.py``'s exec endpoint) or paste it
into a terminal. It reproduces the steps that worked on the laptop spike on
2026-08-31: uv venv, ``freetoken`` from PyPI, the NVFP4 checkpoint from Hugging Face,
a systemd user unit.

The script is generated text, not executed here — FreeToken has no authentication of
its own, so where it listens and who can reach it is the operator's decision, and
the script says so at the top instead of guessing.

The tuning numbers are *measured on the target box* by an inlined copy of the
arithmetic in ``scripts/freetoken/autotune.sh``. That script is the canonical
version; this one is inlined because the machine being provisioned does not have
the Harvis repo on it. Keep the two in step when the formula changes.
"""

from __future__ import annotations

DEFAULT_MODEL_REPO = "FlashML-org/Qwen3.6-35B-A3B-NVFP4"

# Placeholders are ``@@NAME@@`` rather than ``{name}`` so the shell body can keep its
# own braces (``${VAR}``, Caddy blocks) without doubling every one of them.
_TEMPLATE = r"""#!/usr/bin/env bash
# FreeToken inference node bootstrap — generated by Harvis (plugins/inference_nodes).
# Node: @@NODE_NAME@@   Model: @@MODEL_REPO@@   Listen: @@HOST@@:@@PORT@@
#
# READ BEFORE RUNNING. FreeToken has no authentication. Binding to @@HOST@@ means every
# host that can reach port @@PORT@@ can run prompts on this GPU. On a shared or campus
# network put it behind a bearer-token reverse proxy (Caddy example at the bottom) or
# reach it over a private transport (Tailscale, WireGuard, SSH -L) and bind 127.0.0.1.
#
# Needs: Linux, an NVIDIA driver that supports CUDA 13 (driver >= 580), python3.12+,
# ~25 GB free disk for the checkpoint, and network access to PyPI and Hugging Face.
#
# The FT_* tuning numbers below are measured on THIS machine, not copied from the box
# that generated the script. What keeps FreeToken alive is a property of the hardware:
# an 8 GB card needs a 2048-token prefill chunk and a 0.90 memory ratio or the
# scheduler is OOM-killed mid-prompt, and a 24 GB card is wasted at those numbers.
set -euo pipefail

FT_HOME="${FT_HOME:-$HOME/freetoken}"
FT_MODEL_REPO="${FT_MODEL_REPO:-@@MODEL_REPO@@}"
FT_MODEL="${FT_MODEL:-models/@@MODEL_DIR@@}"
FT_PORT="${FT_PORT:-@@PORT@@}"
FT_HOST="${FT_HOST:-@@HOST@@}"
export FT_HOME FT_MODEL_REPO FT_MODEL FT_PORT FT_HOST

echo "==> node @@NODE_NAME@@: installing FreeToken under $FT_HOME"
mkdir -p "$FT_HOME/models"
cd "$FT_HOME"

if ! command -v nvidia-smi >/dev/null 2>&1; then
  echo "nvidia-smi not found — install the NVIDIA driver first." >&2; exit 1
fi
nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader

if ! command -v uv >/dev/null 2>&1; then
  echo "==> installing uv (astral.sh)"
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$PATH"
fi

[ -d venv ] || uv venv --python 3.12 venv
uv pip install --python ./venv/bin/python --upgrade freetoken huggingface_hub

if [ ! -f "$FT_MODEL/config.json" ]; then
  echo "==> downloading $FT_MODEL_REPO (this is ~22 GB)"
  ./venv/bin/python - <<'PY'
import os
from huggingface_hub import snapshot_download
repo = os.environ["FT_MODEL_REPO"]
print("path=" + snapshot_download(repo, local_dir="models/" + repo.rstrip("/").split("/")[-1]))
PY
fi

# ---------------------------------------------------------------- size this machine
echo "==> sizing FreeToken for this machine"
read -r VRAM_TOTAL VRAM_USED <<<"$(nvidia-smi --query-gpu=memory.total,memory.used \
  --format=csv,noheader,nounits | head -1 | tr -d ',')"
RAM_TOTAL_MB="$(awk '/MemTotal/{printf "%d", $2/1024}' /proc/meminfo)"
CORES="$(lscpu 2>/dev/null | awk -F: '/^Core\(s\) per socket/{c=$2} /^Socket\(s\)/{s=$2} END{print (c*s)+0}')"
if [ "${CORES:-0}" -lt 1 ]; then CORES="$(nproc)"; fi
MODEL_MB="$(du -sm "$FT_MODEL" 2>/dev/null | awk '{print $1}')"; MODEL_MB="${MODEL_MB:-0}"

eval "$(./venv/bin/python - "$VRAM_TOTAL" "$RAM_TOTAL_MB" "$CORES" "$MODEL_MB" <<'PY'
import sys
vram, ram, cores, model = (int(float(x)) for x in sys.argv[1:5])

# Prefill scratch is the VRAM one chunk of prefill needs ON TOP of the memory-ratio
# budget. It is what killed the 8 GB laptop at FreeToken's default chunk of 8192, so
# the chunk scales with the card instead of staying at the default.
prefill = 2048 if vram <= 10240 else (4096 if vram <= 17408 else 8192)
scratch = int(450 * prefill / 2048)

# --memory-ratio caps FreeToken's budget as a fraction of TOTAL VRAM. It does not need
# to subtract what a desktop session already holds: --moe-cache-auto sizes itself from
# *free* VRAM. What the ratio must leave behind is the prefill scratch above plus a
# margin for CUDA graphs and fragmentation. Calibrated so an 8 GB card lands on 0.90,
# the value measured to survive a grounded prompt where 0.95 OOM-killed the scheduler.
ratio = max(0.75, min(0.93, round((vram - scratch - int(vram * 0.05)) / vram, 2)))

# KV cache: ~20 KB/token on a GDN-hybrid model, so 16384 tokens is ~0.31 GB. Aim at
# about 4% of the card — enough for a grounded chat with sources, never so much that
# it starves the expert cache.
kv = 8192
for cand in (8192, 16384, 32768, 65536, 131072):
    if cand * 20 / 1024 <= vram * 0.04:
        kv = cand
kv = max(16384, kv) if vram > 6144 else 8192

running = 2 if vram <= 12288 else (4 if vram <= 25600 else 8)
threads = max(4, min(12, cores - 2))

# The constraint people miss: MoE expert weights live in HOST RAM, not on the card.
warn = ""
if model:
    need = model + 4096
    if ram < need:
        warn = ("RAM is tight: a %d GB checkpoint on a %d GB box. FreeToken keeps the "
                "expert weights in system RAM, so expect swapping. Want about %d GB."
                % (model // 1024, ram // 1024, need // 1024))
    elif ram < need + 8192:
        warn = ("RAM is workable but not roomy: %d GB checkpoint on %d GB. Leave the "
                "idle timer on so the RAM comes back between chats."
                % (model // 1024, ram // 1024))

for name, value in (("A_PREFILL", prefill), ("A_RATIO", "%.2f" % ratio), ("A_KV", kv),
                    ("A_RUNNING", running), ("A_THREADS", threads), ("A_SCRATCH", scratch)):
    print("%s=%s" % (name, value))
print("A_WARN=%s" % repr(warn))
PY
)"

cat > "$FT_HOME/freetoken.env" <<EOF
# Measured on this machine by the Harvis provisioning script on $(date -Iseconds).
# ${VRAM_TOTAL} MiB VRAM, $(( RAM_TOTAL_MB / 1024 )) GB RAM, $CORES physical cores.
# Re-run scripts/freetoken/limits.sh from the Harvis repo against this node: these are
# calibrated starting points, the measured ceiling is the number that counts.
FT_HOME=$FT_HOME
FT_MODEL=$FT_MODEL
# FreeToken has no auth. 172.17.0.1 is the Docker bridge only (reachable from a Harvis
# container as host.docker.internal, from nothing on the LAN); 0.0.0.0 is every
# interface, so use it only behind a token proxy or on a private network.
FT_HOST=$FT_HOST
FT_PORT=$FT_PORT
FT_MAX_RUNNING=$A_RUNNING
FT_KV_RESERVE=$A_KV
# One prefill chunk needs ~${A_SCRATCH} MiB outside this budget, plus CUDA graph margin.
FT_MEMORY_RATIO=$A_RATIO
FT_MOE_THREADS=$A_THREADS
FT_MAX_PREFILL=$A_PREFILL
FT_IDLE_MIN=30
FT_WATCHDOG_PROBE_MIN=10
FT_WATCHDOG_MAX_RESTARTS=3
FT_WATCHDOG_PROBE_TIMEOUT=45
EOF
@@OVERRIDES_BLOCK@@
echo "==> settings for this box:"; grep -v '^#' "$FT_HOME/freetoken.env" | grep . | sed 's/^/    /'
if [ -n "${A_WARN:-}" ]; then echo "==> WARNING: $A_WARN" >&2; fi

# ---------------------------------------------------------------------- serve + unit
cat > "$FT_HOME/serve.sh" <<'EOF'
#!/usr/bin/env bash
# Every setting comes from freetoken.env beside this script, so tuning the node never
# means editing it. systemd reads the same file through EnvironmentFile.
set -euo pipefail
cd "$(dirname "$0")"
if [ -f ./freetoken.env ]; then set -a; . ./freetoken.env; set +a; fi
: "${FT_HOME:?FT_HOME is required}"
: "${FT_MODEL:?FT_MODEL is required}"
cd "$FT_HOME"
exec ./venv/bin/ft serve \
  --model "$FT_MODEL" \
  --host "${FT_HOST:-127.0.0.1}" \
  --port "${FT_PORT:-1919}" \
  --max-running-requests "${FT_MAX_RUNNING:-2}" \
  --kv-reserve-tokens "${FT_KV_RESERVE:-16384}" \
  --memory-ratio "${FT_MEMORY_RATIO:-0.90}" \
  --moe-cpu-threads "${FT_MOE_THREADS:-6}" \
  --max-prefill-length "${FT_MAX_PREFILL:-2048}" \
  "$@"
EOF
chmod +x "$FT_HOME/serve.sh"

mkdir -p "$HOME/.config/systemd/user"
cat > "$HOME/.config/systemd/user/freetoken.service" <<EOF
[Unit]
Description=FreeToken inference node (@@NODE_NAME@@)
After=network-online.target

[Service]
EnvironmentFile=$FT_HOME/freetoken.env
ExecStart=$FT_HOME/serve.sh
Restart=on-failure
RestartSec=15
Nice=10

[Install]
WantedBy=default.target
EOF
systemctl --user daemon-reload
systemctl --user enable --now freetoken.service
loginctl enable-linger "$USER" 2>/dev/null || true

echo "==> waiting for the model to load (30-90 s on first start)"
for _ in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:$FT_PORT/health" >/dev/null 2>&1; then break; fi
  sleep 3
done
curl -fsS "http://127.0.0.1:$FT_PORT/v1/models" | head -c 400; echo

cat <<EOF

==> Register this node in Harvis (docker-compose.override.yml, backend environment):
    HARVIS_INFERENCE_NODES: "@@NODE_NAME@@=http://<this-host>:$FT_PORT|dialect=openai|label=@@NODE_NAME@@"
    then: docker compose up -d backend      # restart does not re-read the environment

==> Copy scripts/freetoken/{watchdog.sh,freetoken-watchdog.*} from the Harvis repo onto
    this box and run scripts/freetoken/install-user-units.sh. A node whose scheduler is
    OOM-killed keeps the port open and stays "active" to systemd; the watchdog is what
    notices and restarts it.

==> Optional bearer-token front (Caddyfile), since FreeToken itself has no auth:
    :@@PROXY_PORT@@ {
      @noauth not header Authorization "Bearer <long-random-token>"
      respond @noauth 401
      reverse_proxy 127.0.0.1:$FT_PORT
    }
    and in Harvis use port @@PROXY_PORT@@ with |token_env=FT_NODE_TOKEN in the entry.
EOF
"""


def render_script(
    *,
    node_name: str = "node1",
    model_repo: str = DEFAULT_MODEL_REPO,
    port: int = 1919,
    host: str = "0.0.0.0",
    max_running: int | None = None,
    kv_reserve_tokens: int | None = None,
    memory_ratio: float | None = None,
    moe_cpu_threads: int | None = None,
) -> str:
    """Render the bootstrap script.

    The four tuning arguments default to ``None``, which means *size them on the
    target machine*. That is almost always what you want: the settings that keep
    FreeToken alive are a property of the box, and an earlier version of this
    script baked the 8 GB laptop's numbers into every node it provisioned. Pass a
    value only to pin one; it is appended to the generated ``freetoken.env`` after
    the measured block, so it wins.
    """
    overrides = "\n".join(
        f"{name}={value}"
        for name, value in (
            ("FT_MAX_RUNNING", max_running),
            ("FT_KV_RESERVE", kv_reserve_tokens),
            ("FT_MEMORY_RATIO", memory_ratio),
            ("FT_MOE_THREADS", moe_cpu_threads),
        )
        if value is not None
    )
    overrides_block = (
        'cat >> "$FT_HOME/freetoken.env" <<EOF\n'
        "\n# pinned by the operator, overriding the measured values above\n"
        f"{overrides}\nEOF"
        if overrides
        else "# (nothing pinned by the operator — every value above was measured here)"
    )
    replacements = {
        "@@NODE_NAME@@": node_name,
        "@@MODEL_REPO@@": model_repo,
        "@@MODEL_DIR@@": model_repo.rstrip("/").split("/")[-1],
        "@@PORT@@": str(port),
        "@@PROXY_PORT@@": str(port + 1),
        "@@HOST@@": host,
        "@@OVERRIDES_BLOCK@@": overrides_block,
    }
    script = _TEMPLATE
    for placeholder, value in replacements.items():
        script = script.replace(placeholder, value)
    return script
