"""Render the bootstrap script that turns a fresh Linux box into a FreeToken node.

Served by ``GET /api/inference-nodes/provision-script`` so an operator can pipe it
over an existing SSH host (``remote/ssh_manager.py``'s exec endpoint) or paste it
into a terminal. It reproduces the steps that worked on the laptop spike on
2026-08-31: uv venv, ``freetoken`` from PyPI, the NVFP4 checkpoint from Hugging Face,
a systemd user unit.

The script is generated text, not executed here — FreeToken has no authentication of
its own, so where it listens and who can reach it is the operator's decision, and
the script says so at the top instead of guessing.
"""

from __future__ import annotations

DEFAULT_MODEL_REPO = "FlashML-org/Qwen3.6-35B-A3B-NVFP4"


def render_script(
    *,
    node_name: str = "node1",
    model_repo: str = DEFAULT_MODEL_REPO,
    port: int = 1919,
    host: str = "0.0.0.0",
    max_running: int = 2,
    kv_reserve_tokens: int = 4096,
    memory_ratio: float = 0.95,
    moe_cpu_threads: int = 6,
) -> str:
    model_dir = model_repo.rstrip("/").split("/")[-1]
    return f"""#!/usr/bin/env bash
# FreeToken inference node bootstrap — generated by Harvis (plugins/inference_nodes).
# Node: {node_name}   Model: {model_repo}   Listen: {host}:{port}
#
# READ BEFORE RUNNING. FreeToken has no authentication. Binding to {host} means every
# host that can reach port {port} can run prompts on this GPU. On a shared or campus
# network put it behind a bearer-token reverse proxy (Caddy example at the bottom) or
# reach it over a private transport (Tailscale, WireGuard, SSH -L) and bind 127.0.0.1.
#
# Needs: Linux, an NVIDIA driver that supports CUDA 13 (driver >= 580), python3.12+,
# ~25 GB free disk for the checkpoint, and network access to PyPI and Hugging Face.
set -euo pipefail

FT_HOME="${{FT_HOME:-$HOME/freetoken}}"
FT_MODEL_REPO="${{FT_MODEL_REPO:-{model_repo}}}"
FT_PORT="${{FT_PORT:-{port}}}"
FT_HOST="${{FT_HOST:-{host}}}"

echo "==> node {node_name}: installing FreeToken under $FT_HOME"
mkdir -p "$FT_HOME/models"
cd "$FT_HOME"

if ! command -v nvidia-smi >/dev/null 2>&1; then
  echo "nvidia-smi not found — install the NVIDIA driver first." >&2; exit 1
fi
nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader

if ! command -v uv >/dev/null 2>&1; then
  echo "==> installing uv (astral.sh)"
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$PATH"
fi

[ -d venv ] || uv venv --python 3.12 venv
uv pip install --python ./venv/bin/python --upgrade freetoken huggingface_hub

if [ ! -f "models/{model_dir}/config.json" ]; then
  echo "==> downloading $FT_MODEL_REPO (this is ~22 GB)"
  ./venv/bin/python - <<'PY'
import os
from huggingface_hub import snapshot_download
repo = os.environ.get("FT_MODEL_REPO", "{model_repo}")
print("path=" + snapshot_download(repo, local_dir="models/" + repo.split("/")[-1]))
PY
fi

cat > serve.sh <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd "\\$(dirname "\\$0")"
exec ./venv/bin/ft serve \\\\
  --model models/{model_dir} \\\\
  --host "\\${{FT_HOST:-{host}}}" --port "\\${{FT_PORT:-{port}}}" \\\\
  --max-running-requests {max_running} \\\\
  --kv-reserve-tokens {kv_reserve_tokens} --memory-ratio {memory_ratio} \\\\
  --moe-cpu-threads {moe_cpu_threads} "\\$@"
EOF
chmod +x serve.sh

mkdir -p "$HOME/.config/systemd/user"
cat > "$HOME/.config/systemd/user/freetoken.service" <<EOF
[Unit]
Description=FreeToken inference node ({node_name})
After=network-online.target

[Service]
Environment=FT_HOST=$FT_HOST
Environment=FT_PORT=$FT_PORT
ExecStart=$FT_HOME/serve.sh
Restart=on-failure
RestartSec=15
Nice=10

[Install]
WantedBy=default.target
EOF
systemctl --user daemon-reload
systemctl --user enable --now freetoken.service
loginctl enable-linger "$USER" 2>/dev/null || true

echo "==> waiting for the model to load (30-90 s on first start)"
for _ in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:$FT_PORT/health" >/dev/null 2>&1; then break; fi
  sleep 3
done
curl -fsS "http://127.0.0.1:$FT_PORT/v1/models" | head -c 400; echo

cat <<EOF

==> Register this node in Harvis (docker-compose.override.yml, backend environment):
    HARVIS_INFERENCE_NODES: "{node_name}=http://<this-host>:$FT_PORT|dialect=openai|label={node_name}"
    then: docker compose restart backend

==> Optional bearer-token front (Caddyfile), since FreeToken itself has no auth:
    :{port + 1} {{
      @noauth not header Authorization "Bearer <long-random-token>"
      respond @noauth 401
      reverse_proxy 127.0.0.1:$FT_PORT
    }}
    and in Harvis use port {port + 1} with |token_env=FT_NODE_TOKEN in the entry.
EOF
"""
