---
# GitLab Runner Secret Template
# Copy this to gitlab-runner-secret.yaml and fill in your actual values
# DO NOT commit the actual secret file to git!

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab-runner
type: Opaque
stringData:
  # Your GitLab instance URL (e.g., https://gitlab.com or https://gitlab.yourdomain.com)
  gitlab-url: "https://gitlab.com"
  
  # Your GitLab runner registration token
  # Get this from: GitLab Project -> Settings -> CI/CD -> Runners -> New project runner
  registration-token: "YOUR_REGISTRATION_TOKEN_HERE"
