apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvis-document-worker
  namespace: ai-agents
  labels:
    app.kubernetes.io/name: harvis-ai
    app.kubernetes.io/component: document-worker
  annotations:
    description: "Async document generation worker - lightweight image (~200MB)"
spec:
  replicas: 2  # Scale based on load - each worker processes one job at a time
  selector:
    matchLabels:
      app.kubernetes.io/name: harvis-ai
      app.kubernetes.io/component: document-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: harvis-ai
        app.kubernetes.io/component: document-worker
    spec:
      # Run on dulc3-os node where artifacts PVC is located
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - dulc3-os

      containers:
        - name: document-worker
          # Lightweight document worker image (~200MB vs 8GB+ backend)
          # Built from Dockerfile.document-worker
          image: "dulc3/harvis-document-worker:v2.28.4"
          imagePullPolicy: Always
          # No command needed - Dockerfile CMD handles it

          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: 2000m
              # No GPU needed for document generation

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: harvis-ai-backend-secret
                  key: database-url

            - name: OLLAMA_URL
              value: "http://harvis-ai-merged-backend:11434"

            - name: BACKEND_URL
              value: "http://harvis-ai-backend.ai-agents.svc.cluster.local:8000"

            # Output directory for generated documents
            - name: ARTIFACT_STORAGE_DIR
              value: "/data/artifacts"

            - name: ENVIRONMENT
              value: "production"

            - name: LOG_LEVEL
              value: "INFO"

            # Run document generation locally in pod (Docker not available in K8s)
            - name: CODE_EXECUTOR_LOCAL
              value: "true"

            # Worker-specific settings
            - name: WORKER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WORKER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WORKER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          volumeMounts:
            - name: artifacts-storage
              mountPath: /data/artifacts

          # Health checks
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - "import asyncpg; import openpyxl; print('healthy')"
            initialDelaySeconds: 15
            periodSeconds: 30

          readinessProbe:
            exec:
              command:
                - python
                - -c
                - "import asyncpg; import openpyxl; print('ready')"
            initialDelaySeconds: 5
            periodSeconds: 10

      volumes:
        - name: artifacts-storage
          persistentVolumeClaim:
            claimName: harvis-artifacts-pvc

      # Restart policy
      restartPolicy: Always

      # Graceful shutdown
      terminationGracePeriodSeconds: 30

---
# HorizontalPodAutoscaler for automatic scaling based on queue depth
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harvis-document-worker-hpa
  namespace: ai-agents
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harvis-document-worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metric:
          name: document_jobs_pending
          selector:
            matchLabels:
              queue: generate-document
        target:
          type: AverageValue
          averageValue: "5"  # Scale up when 5+ pending jobs per worker
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60

---
# PodDisruptionBudget to ensure minimum availability during updates
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: harvis-document-worker-pdb
  namespace: ai-agents
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: harvis-ai
      app.kubernetes.io/component: document-worker

---
# ServiceMonitor for Prometheus metrics (optional)
apiVersion: v1
kind: Service
metadata:
  name: harvis-document-worker-metrics
  namespace: ai-agents
  labels:
    app.kubernetes.io/name: harvis-ai
    app.kubernetes.io/component: document-worker
spec:
  selector:
    app.kubernetes.io/name: harvis-ai
    app.kubernetes.io/component: document-worker
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
  clusterIP: None  # Headless service for direct pod access
